### ISSUE TITLE
Where did all the nice colors go

### ISSUE THREAD

**Issue by mfour-merickson** [stefanzweifel/laravel-stats#104]
Just installed 1.1.1 and the output no longer shows the nice colors.  

![image](https://user-images.githubusercontent.com/31225533/31972026-76c95590-b8d3-11e7-9d8e-7ac3922bcf84.png)

**Comment by stefanzweifel** [comment]
Do you mean the colors which are in the screenshot in the README? That's just a formatted version of the output I've made with [carbon](https://carbon.now.sh).

I will update the README with a real screenshot, so there are no misunderstandings.

The output looks the exactly the same as yours in my projects:

![bildschirmfoto 2017-10-25 um 08 26 19](https://user-images.githubusercontent.com/1080923/31983742-d61676aa-b95e-11e7-94df-bbc758c938b6.png)

**Comment by mfour-merickson** [comment]
Ah gotcha, it was just "misleading"  :-)
