### ISSUE TITLE
Using Docker for unit testing

### ISSUE THREAD

**Issue by aiiro** [stefanzweifel/laravel-stats#107]
Hi!

I'd like to propose using docker for unit testing.
Now TravisCI runs multiple PHP versions tests when the PR is created.
I think that it's useful if developers can run phpunit with those versions before creating the new PR.

I think Docker Compose can make it easy for developers to run phpunit with multiple versions.

Thanks.

**Comment by stefanzweifel** [comment]
Hey there

Personally, I would like to keep it as it is. The code is still quite simple and I think in the future there shouldn't be any conflicts with newer PHP versions.

But thanks for the idea!

**Comment by aiiro** [comment]
I got it. Thank you for considering!
