### ISSUE TITLE
Add Policies to the Statistics

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/laravel-stats#11]
We somehow have to find a good way to recognize Policies.

[ComponentConfiguration](https://github.com/stefanzweifel/laravel-stats/blob/master/src/ComponentConfiguration.php#L71)

**Comment by sebdesign** [comment]
`Illuminate\Auth\Access\Gate::policies()` returns an array or registered policies.

**Comment by stefanzweifel** [comment]
Nice. Didn't know about that. Thanks!

**Comment by sebdesign** [comment]
I'll submit a PR. :)
