### ISSUE TITLE
[Feature request] Recognize tests when they extend Tests\TestCase

### ISSUE THREAD

**Issue by manniL** [stefanzweifel/laravel-stats#111]
In Laravel, the default tests (and subsequently tests build through `php artisan make:test <NAME>` extend the `Tests\TestCase` class, not the `PHPUnit\Framework\TestCase` class ([reference](https://laravel.com/docs/5.5/testing#creating-and-running-tests)).

So all of my tests are not recognized by Laravel Stats currently:
![screenshot from 2017-11-14 12-09-15](https://user-images.githubusercontent.com/640208/32776961-a904da04-c934-11e7-811c-d7fb1629ca38.png)

Could the recognition constraints for tests be changed?

**Comment by stefanzweifel** [comment]
The config currently doesn‘t ship with the tests folders, because the testsuite of the package itself has issues with it.

Currently working on a fix for that.

**Comment by manniL** [comment]
Oh, I see. Thanks a lot for clarifying this! ☺️

**Comment by stefanzweifel** [comment]
Just a heads up: I've just tagged `v1.3.3` which now enables the `tests`-folder by default. When used in a new project the tests now appear by default in the output table.

eaedc4dee84043a985b0cf7d337cf7b479b62a75
