### ISSUE TITLE
Update to Laravel 5.6

### ISSUE THREAD

**Issue by rjsworking** [stefanzweifel/laravel-stats#118]
Hi
Laravel 5.6 is coming this week. The package doesn't install on L5.6 due to Illuminate 5.5.* requirements.

Thanks in advance

**Comment by stefanzweifel** [comment]
Hi,

I'm aware that Laravel 5.6 will be released tomorrow (Wednesday). I will update the requirements this evening (or someone can send a Pull Request)

**Comment by stefanzweifel** [comment]
I've prepared a PR (#119). If you want you could update to `dev-laravel-56-support` or wait till I tag a new release.

**Comment by stefanzweifel** [comment]
#119 has been merged and a new release has been tagged: https://github.com/stefanzweifel/laravel-stats/releases/tag/v1.6.0
