### ISSUE TITLE
Add Middleware to Statistics

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/laravel-stats#12]
Middleware don't extend a base class or implement an Interface. So we have to find a good way to reliably detect Middlewares.

[ComponentConfiguration](https://github.com/stefanzweifel/laravel-stats/blob/master/src/ComponentConfiguration.php#L75)

**Comment by thecrypticace** [comment]
Some possible heuristics:

0. Typically reside in the `App\Http\Middleware` namespace
1. Have a `handle` method with two or more parameters
2. The first is usually named `$request` and (sometimes) type hinted with `Illuminate\Http\Request`
3. The second is usually named `$next` and typically type hinted with `Closure`.

**Comment by stefanzweifel** [comment]
@thecrypticace I don't like the first option (0.) because I don't want to rely on the default namespace. I work on a project where we don't follow the normal `App`-namespace and this approach would ignore our Middlewares.

But I think I could implement a mix of the rest. Find classes which have a `handle`-method with said signature. As a second option I could also look into the `Http/Kernel.php` use the declared Middlewares.

Thanks for the input 👍

**Comment by thecrypticace** [comment]
Yeah, renamed namespaces will cause an issue. You can also read the composer.json file as an attempt to guess the namespace.

The `Http/Kernel` bit is also a pretty good idea.

**Comment by mfour-merickson** [comment]
+1

**Comment by sebdesign** [comment]
`Illuminate\Routing\Router` has `getMiddleware` and `getMiddlewareGroups` methods that might be helpful.

**Comment by stefanzweifel** [comment]
Added in #28
