### ISSUE TITLE
Classes from vendor packages shouldn't count to statistics

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/laravel-stats#13]
As [Adam pointed out](https://twitter.com/adamwathan/status/917077190818304000) the package currently counts Components from vendor packages to statistics.

That shouldn't happen.

The [`getDeclaredClass`](https://github.com/stefanzweifel/laravel-stats/blob/master/src/ClassFinder.php#L36)-method should run a filter on the collection to remove all files which are stored in `vendor/*`

**Comment by thecrypticace** [comment]
You can use reflection to do this.

ReflectionClass::getFileName will give you the full path to the file that declared the class (and return false if it is an internal PHP class)

I'll prep a PR sometime today.

**Comment by stefanzweifel** [comment]
The package already relies heavely on the ReflectionClass. I've also create my own [`ReflectionClass`](https://github.com/stefanzweifel/laravel-stats/blob/master/src/ReflectionClass.php) for this project (but I think I should rename it to something else. I think it only causes confusion with the "native" PHP `ReflectionClass`).

The check if a Class belongs to a vendor-package could also happen [here](https://github.com/stefanzweifel/laravel-stats/blob/master/src/ComponentSort.php#L21), where the classes are sorted into Component buckets.

**Comment by thecrypticace** [comment]
1. Yep, I noticed that. I quite like the idea of decorating ReflectionClass like you have.
2. Imho, I don't think that method be the best spot to put the check. Feels a bit strange.

I've opened a PR and we can discuss specifics there.

**Comment by stefanzweifel** [comment]
Closed in #15. Thanks again for the PR.
