### ISSUE TITLE
ErrorException : "continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by RicardoRamirezR** [stefanzweifel/laravel-stats#135]
Hi there, I just installed your package and tried to run `php artisan stats`but got:

![Captura de pantalla 2019-03-14 a la(s) 3 19 42 p  m](https://user-images.githubusercontent.com/6526545/54389063-3c62d380-466d-11e9-809f-340e8fc5e8af.png)

I've added `SebastianBergmann\PHPLOC`to the 'ignored_namespaces' in `config/stats.php` without luck.

Any tip will be very welcome, thanks.

**Comment by shawnlindstrom** [comment]
Did you have this on latest Homestead running PHP 7.3? Try:

`php7.2 artisan stats`

**Comment by RicardoRamirezR** [comment]
Actually, I have that on `valet` and I don't' have 7.2 only 7.3.2

**Comment by RicardoRamirezR** [comment]
There is a PR on this https://github.com/stefanzweifel/laravel-stats/pull/129#issue-238306303

**Comment by HDVinnie** [comment]
getting same error here on php7.3

**Comment by stefanzweifel** [comment]
Yes, unfortunately the package is currently broken on PHP 7.3. As described in https://github.com/stefanzweifel/laravel-stats/pull/129#issue-238306303, this comes from the phploc package.

I will create a PR to fix this issue over the next days. I hope I can tag a new php7.3 compatible version of laravel-stats in the next 2 weeks.

**Comment by infostreams** [comment]
The version at https://github.com/sebastianbergmann/phploc/edit/master/src/Analyser.php actually has fixed all of these warnings already...

**Comment by stefanzweifel** [comment]
Oh yes, you're right. In https://github.com/sebastianbergmann/phploc/commit/6834fdaaf288fff461602015c2f04d3b981ad787 a fix for PHP 7.3 has been applied.

The changes have not yet been tagged in a new stable release (Changes since the last release: https://github.com/sebastianbergmann/phploc/compare/4.0.1...master).
Will reach out to them, to ask if they could release the fixes.

Don't like the idea of changing the dependency to a `dev-master` version.

**Comment by abhisheksarmah** [comment]
i am also getting the same error. Using valet.

**Comment by stefanzweifel** [comment]
I've created an issue on the repo: https://github.com/sebastianbergmann/phploc/issues/190.
Will update my PR (#129) with further changes to make the package compatible with PHP 7.3

**Comment by stefanzweifel** [comment]
`master` is now compatible with PHP7.3. Will do some last testing and then tag a new release.
