### ISSUE TITLE
It is not compatible with PHP 7.3

### ISSUE THREAD

**Issue by burhanmt** [stefanzweifel/laravel-stats#137]
After trying with PHP 7.3.1, I encountered this issue:
"
...
In Analyser.php line 92:
                                                                                           
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
  ..                                                                                         
"

**Comment by stefanzweifel** [comment]
Hm, this comes from the `phploc` depedency. Could you also run `composer upgrade phploc/phploc`?

**Comment by stefanzweifel** [comment]
I've updated the release notes with a mention to also update the phploc dependency. 
Unfortunately, I don't see an easy way to enforce a certain `phploc` version for PHP 7.2 / PHP 7.3 and another version for lower PHP versions.
