### ISSUE TITLE
rescue function not exist in Lumen

### ISSUE THREAD

**Issue by maxsky** [stefanzweifel/laravel-stats#138]
`rescue` function at `laravel/framework/src/Illuminate/Foundation/helpers.php` with Laravel framework, but Lumen not exist.

```php
if (! function_exists('rescue')) {
    /**
     * Catch a potential exception and return a default value.
     *
     * @param  callable  $callback
     * @param  mixed  $rescue
     * @return mixed
     */
    function rescue(callable $callback, $rescue = null)
    {
        try {
            return $callback();
        } catch (Throwable $e) {
            report($e);

            return value($rescue);
        }
    }
}
```

**Comment by maxsky** [comment]
Same problem with `resolve` function in `helpers.php`.

**Comment by stefanzweifel** [comment]
Can you tell me which Lumen version you are using?

**Comment by stefanzweifel** [comment]
Just tagged [`v1.9.1`](https://github.com/stefanzweifel/laravel-stats/releases/tag/v1.9.1) which fixes those Lumen compatibility issues.

**Comment by maxsky** [comment]
Thanks, my current Lumen version is `5.7.8`
