### ISSUE TITLE
ide helper conflict / error

### ISSUE THREAD

**Issue by mfour-merickson** [stefanzweifel/laravel-stats#14]
If I have the _ide_helper.php in the directory, the following is produced. If I delete the file, all is good but obviously ide-helper doesn't work :-)

```
❯ art stats              
PHP Fatal error:  Cannot declare class Artisan, because the name is already in use in /Users/merickson/Documents/code/laravel/l5-sandbox/_ide_helper.php on line 12949

                                                                    
  [Symfony\Component\Debug\Exception\FatalErrorException]           
  Cannot declare class Artisan, because the name is already in use  
 ```

**Comment by stefanzweifel** [comment]
Yeah, could you publish the config file with `php artisan vendor:publish --provider="Wnx\LaravelStats\StatsServiceProvider"` and add the filename to to the `ignore.files` array and try that again?

**Comment by mfour-merickson** [comment]
Still produces error

```
        'files' => [
          '/Users/merickson/Documents/code/laravel/l5-sandbox/_ide_helper.php'   
            // 'helpers.php'
            // 'twig.php'
        ]
```

and command execution

```
❯ art stats                    
PHP Fatal error:  Cannot declare class Artisan, because the name is already in use in /Users/merickson/Documents/code/laravel/l5-sandbox/_ide_helper.php on line 12949

                                                                    
  [Symfony\Component\Debug\Exception\FatalErrorException]           
  Cannot declare class Artisan, because the name is already in use  
                                                                    
```

**Comment by mfour-merickson** [comment]
Very crude workaround for the time being (I dont like this but best I can think of)

```
$ rm _ide_helper.php && art stats && art ide-helper:generate
```

**Comment by mfour-merickson** [comment]
On a whim, I tried the following (ignore rule) and it worked as expected

```
        'files' => [
          '_ide_helper.php'   
            // 'helpers.php'
            // 'twig.php'
        ]
```

**Comment by stefanzweifel** [comment]
Hm, the package currently only uses the [filenames](https://github.com/stefanzweifel/laravel-stats/blob/master/src/ClassFinder.php#L110). This should probably changed to be paths relative to the applications base_path.

**Comment by mfour-merickson** [comment]
@stefanzweifel Let me know when you have updated and I will test again (or I guess I will see it here) ;-)

**Comment by mfour-merickson** [comment]
@stefanzweifel BTW, nice work so far

**Comment by stefanzweifel** [comment]
@mfour-merickson Thanks so much! I hope I can release the final 1.0.0 version by the end of this week.

**Comment by stefanzweifel** [comment]
The `_ide_helper.php` file is now completely ignored by the package: e2d13f5631071229a24c61fe9bc410fdc60b33a7
