### ISSUE TITLE
Classifying Traits

### ISSUE THREAD

**Issue by lasmanis** [stefanzweifel/laravel-stats#142]
What about Traits? Do you guys think it would be useful to include them with a separate Classifier?

I've tested this on my fork: https://github.com/lasmanis/laravel-stats/tree/detect-traits

If you think it would be useful, I'd be happy to send you a PR.

Cheers!

**Comment by stefanzweifel** [comment]
Hm, I think Traits is a bit too broad. I would like to keep the core Classifiers of the project Laravel specific.

@nunomaduro is currently working on a project similar to stats. It will show how many Traits a project has:

https://twitter.com/enunomaduro/status/1107338120561913857


---

On the other hand, stats might ship with some optional Classifiers in the future. Like the one you've written in your fork. Users could just add them to the [`custom_component_classifier`](https://github.com/stefanzweifel/laravel-stats#create-your-own-classifiers)-array.

I might add some classifiers in the future.
