### ISSUE TITLE
Finder Facade abandoned

### ISSUE THREAD

**Issue by oriceon** [stefanzweifel/laravel-stats#184]
stefanzweifel/laravel-stats-phploc uses sebastian/finder-facade wich was abandoned...

**Comment by stefanzweifel** [comment]
Hey 👋

Thanks for pointing this out! 
The issue is technically related to our `phploc`-fork (https://github.com/stefanzweifel/phploc), but I will keep it open here anyway.

I've also noticed that composer throws a bunch of notices, as duplicate namespaces are detected.
