### ISSUE TITLE
Code to test ration ... like the concept

### ISSUE THREAD

**Issue by mfour-merickson** [stefanzweifel/laravel-stats#21]
After reviewing `rake test` i am intrigued by the Code To Test Ratio metric.  Would love to see this when test support has been added.

![image](https://user-images.githubusercontent.com/31225533/31322274-98503c88-ac49-11e7-8340-4d8cdb4cfd55.png)

**Comment by stefanzweifel** [comment]
Code to Test Ratio has been implemented in #109 and has been merged to `master`. Tagging a new release very soon.
