### ISSUE TITLE
Add Support for PhpUnit 10 and Laravel 10

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/laravel-stats#214]
See https://github.com/stefanzweifel/laravel-stats/pull/213#issuecomment-1472087583

**Comment by denisdulici** [comment]
Thanks @stefanzweifel for your effort, appreciate 🙏

**Comment by stefanzweifel** [comment]
laravel-stats can now be installed in fresh Laravel 10 projects that use PHPUnit 10. We've updated our test suite in #217 to also test the package against different versions of PHPUnit, so that this mishap doesn't happen again.

Thanks for bringing this to my attention @denisdulici. 🙌

**Comment by denisdulici** [comment]
Thanks @stefanzweifel, it worked like a charm 🙏
