### ISSUE TITLE
Conflicts with ide-helper package

### ISSUE THREAD

**Issue by manniL** [stefanzweifel/laravel-stats#24]
Unfortunately, the `artisan stats` command is in conflict with the generated files from barryvdhs [Laravel IDE helper](https://github.com/barryvdh/laravel-ide-helper/).

When using the command while the ide helper files exist, the following error is thrown:

> PHP Fatal error:  Cannot declare class App, because the name is already in use in /path/to/_ide_helper.php on line 13814

I know that there can't be a fix for every package conflict, but the laravel ide helper one is very popular among PHPStorm users because it enables autocomplete for them.

**How to reproduce**

1. Install the linked package as well as laravel-stats
2. Use the command `php artisan ide-helper:meta && php artisan ide-helper:models -n && php artisan ide-helper:generate`. The files are now generated
3. Try to use `php artisan stats`
4. See the error

**Comment by stefanzweifel** [comment]
Duplicate to #14.

Can be resolved by publishing the config file and add the **filename** to the `ignore.files`-array. I'm working on a fix that entire filepaths can be set to be ignored.

(Would also be nice if those errors would never be thrown in the first place)

**Comment by stefanzweifel** [comment]
But I will probably add the `_ide_helper.php`file to the default list of ignored files as the package is so popular.

**Comment by manniL** [comment]
That what I wanted to recommend too 😋
