### ISSUE TITLE
Display Number of Routes

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/laravel-stats#44]
I thought about adding the number of routes in a separate row at the bottom of the output table or in a second table. 

It could look like this:

<img width="668" alt="bildschirmfoto 2017-10-12 um 22 05 46" src="https://user-images.githubusercontent.com/1080923/31516687-b1f6a8fe-af99-11e7-8ac4-3e2790d6b111.png">

*(This would be something for 2.0)*

Thoughts?

**Comment by jerguslejko** [comment]
👎 for me

**Comment by RamonSmit** [comment]
Well I have to admit, I quite like the idea! I have no clue how many routes are defined in our projects!

**Comment by scottzirkel** [comment]
I could see a use for it. Though I might format it a bit differently. Maybe closer to the rest of the formating?

````
+-----------+--------+----+---------------+--------+
| Routes    | 999    |    | API Routes    | 999    |
+-----------+--------+----+---------------+--------+
````

**Comment by jerguslejko** [comment]
I tend to have `routes/web.php`, `routes/admin.php`, `routes/api.php`, `routes/hooks.php`. How would you fit all of these "categories" into the table? Also, I can easily imagine that someone would use naming structure as `routes/frontend.php`, `routes/backend.php`, `routes/whatever.php`.

It's worth noting that this feature, counting routes, is currently possible even without this package.

```php
$router->getRoutes()->count()
```

or

```
$ php artisan route:list | grep "/api" | nc -l
```

I do realise that this is not the best or the most seamless way to analyse routes, but it is possible. However, analysing number of methods or LOC is not, and that is what this package should focus on.

**Comment by stefanzweifel** [comment]
I have to agree with @jerguslejko. The original idea of the package was to analyze classes and components of a project. Laravel already ships with `route:list` which does as good job.
