### ISSUE TITLE
Suggestion: Different output formats?

### ISSUE THREAD

**Issue by jakebathman** [stefanzweifel/laravel-stats#48]
I've written a helper before that took CLOC output and formatted it in an HTML table.

If that's something that would be useful as a command switch (e.g. `--output=stats.html`) I'll write it up and submit a PR.

**Comment by stefanzweifel** [comment]
Hi

Yeah I think that would be a great addition which should be added in a future version. With v1.0 I first would like to finalize the internal structure how the stats are stored.

After the structure is finalized it should be easy to add different output formats. (If you spin the idea further you could write a CI service which ensures that your controller methods are not longer than 25 lines 🤔 )

**Comment by jakebathman** [comment]
I'd be the first to break that controller method rule 😆 

I'll start hacking on an output formatter for html and JSON maybe, but won't worry about a PR until this is happy and stable. Thanks!
