### ISSUE TITLE
StyleCI is not working

### ISSUE THREAD

**Issue by jerguslejko** [stefanzweifel/laravel-stats#52]
Could you investigate this?

**Comment by stefanzweifel** [comment]
I've deactivated it. I think StyleCI couldn't write to the PR-Branches.

Will test it again.

**Comment by jerguslejko** [comment]
Any updates on this?

**Comment by stefanzweifel** [comment]
Just reconnected the Repo. Give me a sec ...

**Comment by jerguslejko** [comment]
Few things:

- use `preset: laravel` config option
- select "Automatically directly commit fixes to the same branch"

**Comment by stefanzweifel** [comment]
I just wonder if this will work with PRs from other Contributors. We will see 😉
