### ISSUE TITLE
Inconsistent PHP version requirement

### ISSUE THREAD

**Issue by mnabialek** [stefanzweifel/laravel-stats#57]
In [readme](https://github.com/stefanzweifel/laravel-stats/blob/master/README.md) there is info about PHP 7.0, in [composer.json](https://github.com/stefanzweifel/laravel-stats/blob/master/composer.json) there is info about PHP 7.0 but when installing via composer in release there is:

    "require": {
        "php": "^7.1",
        "illuminate/console": "^5.5",
        "illuminate/support": "^5.5",
        "phploc/phploc": "^4.0",
        "symfony/finder": "^3.3"
    },

so when trying to install it seems PHP 7.1 is required. So which one is true - is PHP 7.0 required or PHP 7.1?

**Comment by stefanzweifel** [comment]
It's going to be 7.0. The `1.0.0-beta` release is still on 7.1. 

Sorry for the confusion. As soon as I release 1.0.0 the README will reflect the real php requirements.
