### ISSUE TITLE
Controllers do not need to extend Illuminate\Routing\Controller

### ISSUE THREAD

**Issue by jerguslejko** [stefanzweifel/laravel-stats#59]
This check is actually incorrect as controllers do not need to extend `Illuminate\Routing\Controller`.

https://github.com/stefanzweifel/laravel-stats/blob/ee15db03fd906b1db67d6730226208e7bc14db6a/src/ComponentConfiguration.php#L19

**Comment by stefanzweifel** [comment]
Didn't know about that. Here's the link to the [docs](https://laravel.com/docs/5.5/controllers#basic-controllers).

> Note that the controller extends the base controller class included with Laravel. The base class provides a few convenience methods such as the  middleware method, which may be used to attach middleware to controller actions:

> 🚨 **Controllers are not required to extend a base class. However, you will not have access to convenience features such as the middleware, validate, and dispatch methods.**

**Comment by jerguslejko** [comment]
I think, I'd be better to load a list of routes and extract list of controllers from that.
