### ISSUE TITLE
does it can be used with php7.0?

### ISSUE THREAD

**Issue by tawenxi** [stefanzweifel/laravel-stats#69]
when I install this package with composert it report a error like this:
- wnx/laravel-stats v1.0.0-beta requires php ^7.1 -> your PHP version (7.0.24) does not satisfy that requirement.

can you help me? Thank you.

**Comment by jkujawski** [comment]
As far as I remember from the discussion here, beta version still requires PHP 7.1, the target is 7.0 though on the stable version.

**Comment by stefanzweifel** [comment]
You could also run the `dev-master` version by installing the package like this:

```shell
composer require "wnx/laravel-stats:dev-master"
```

Please note that there is currently a bug (#67) in the command. To get the command running you would have to disable your Routes which uses a `Closure`.

**Comment by stefanzweifel** [comment]
Also see #19
