### ISSUE TITLE
Category 'Others'

### ISSUE THREAD

**Issue by jerguslejko** [stefanzweifel/laravel-stats#73]
I propose we introduce a new category named 'Others'. This would include all classes that are not picked up by any of the classifiers and therefore display statistics for the custom stuff as well.

I have an implementation in mind. What do you think?

**Comment by stefanzweifel** [comment]
Yeah that could be useful. With the new "Others" category you would actually see how many classes and LoC your application has.
In it's current state you would only see the "Basic" Laravel components and you would have to use the `phploc` command yourself to get a useful number.

I'm open for PRs 👍
