### ISSUE TITLE
[New stat] Listeners

### ISSUE THREAD

**Issue by LasseRafn** [stefanzweifel/laravel-stats#75]
Would be cool to add listeners as well. I don't know if its already planned? 🤔 

Anyway, if it's not and you would accept a PR for this, I'd gladly put some work into this at some point.

**Comment by stefanzweifel** [comment]
Not yet planned but only because I forgot that they existed 😂 
I'm open also open for tested PRs.

**Comment by stefanzweifel** [comment]
Support for Event Listener has been added in #108. I will tag a new release in the next days.
